apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_SERVER: <api-server>:<NodePort>
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
data:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: <Base64-Enocded-userName>
  ARGOCD_PASSWORD: <Base64-Enocded-userName>
